version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ws-chat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bzll1bux7fo7"
s3_prefix = "ws-chat"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
image_repositories = []
